### ISSUE TITLE
6.2.1

### ISSUE THREAD

**Issue by vpelss** [webvitalii/page-list#11]
No longer works with 6.2.1

Just shows shortcode on screen:
https://emogic.com/software/

**Comment by webvitalii** [comment]
@vpelss It works for me on 6.2.1
Please check if this issue caused by other plugins or active theme on your website.

**Comment by vpelss** [comment]
It had something to do with:
https://wptavern.com/wordpress-6-2-1-update-breaks-shortcode-support-in-block-templates

Now that 6.2.2 was released, it is working again.

I assume you don't use block themes

**Comment by vpelss** [comment]
thanks

**Comment by webvitalii** [comment]
Yes, after looking into this issue I found that WordPress disabled shortcode execution in WordPress 6.2.1 for full-website editing.
And I was testing in the old-school WordPress editor and it worked as expected.

https://wordpress.org/support/topic/wordpress-v6-2-1-breaks-the-shortcode-block-in-templates/

I am extremely surprised how they disabled that feature which broke so many plugins.
Please try to update to WordPress 6.2.2 and see if that works.

**Comment by baby-gnu** [comment]
As it's not working in page templates I opened #13.
